# Generated by Django 5.1.3 on 2024-11-20 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pass_hash',
        ),
    ]
